name: crop_monitoring_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^10.0.0
  sqflite: ^2.2.7+1
  path_provider: ^2.0.15
  connectivity_plus: ^4.0.2
  geolocator: ^14.0.0  
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geoxml: ^2.6.2
  flutter_map_cancellable_tile_provider: ^2.0.0
  fl_chart: ^0.71.0
  intl: ^0.19.0
  path: ^1.8.3
  file_picker: ^8.1.7 
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
